# Makefile for kividb-operator.
#
# Targets follow the conventions of a kubebuilder-scaffolded project even
# though this repo was hand-written rather than generated by the
# kubebuilder CLI. Run `make help` for a summary.

SHELL := /usr/bin/env bash
.SHELLFLAGS := -eu -o pipefail -c

# ---------------------------------------------------------------------------
# Version / image coordinates
# ---------------------------------------------------------------------------

VERSION ?= $(shell cat VERSION 2>/dev/null || echo 0.1.0)

REGISTRY   ?= quay.io/kividbio
IMG        ?= $(REGISTRY)/kividb-operator:$(VERSION)
AGENT_IMG  ?= $(REGISTRY)/kividb-operator-agent:$(VERSION)
GUI_IMG    ?= $(REGISTRY)/kividb-operator-gui:$(VERSION)

CHART_DIR  := charts/kividb-operator

# CRD manifests are hand-written (see config/crd/bases) rather than
# generated; controller-gen is invoked here on a best-effort basis only --
# it is not a hard dependency of this repo.
CONTROLLER_GEN := $(shell command -v controller-gen 2>/dev/null)

.DEFAULT_GOAL := help

# ---------------------------------------------------------------------------
# Codegen (best-effort: controller-gen is not guaranteed to be installed)
# ---------------------------------------------------------------------------

.PHONY: manifests
manifests: ## Regenerate CRD/RBAC manifests via controller-gen, if installed.
	@if [ -n "$(CONTROLLER_GEN)" ]; then \
		echo ">> running controller-gen (manifests)"; \
		$(CONTROLLER_GEN) rbac:roleName=kividb-operator-manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases; \
	else \
		echo ">> controller-gen not found on PATH -- skipping 'make manifests'."; \
		echo ">> config/crd/bases/kividb.io_kividbclusters.yaml and config/rbac/role.yaml are"; \
		echo ">> hand-written in this repo; install controller-gen (sigs.k8s.io/controller-tools/cmd/controller-gen)"; \
		echo ">> and re-run this target if you change the Go API types or RBAC markers."; \
	fi

.PHONY: generate
generate: ## Regenerate deepcopy code via controller-gen, if installed.
	@if [ -n "$(CONTROLLER_GEN)" ]; then \
		echo ">> running controller-gen (object)"; \
		$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..." 2>/dev/null || \
		$(CONTROLLER_GEN) object paths="./..."; \
	else \
		echo ">> controller-gen not found on PATH -- skipping 'make generate'."; \
		echo ">> api/v1alpha1/zz_generated.deepcopy.go was hand-written in this repo; install"; \
		echo ">> controller-gen and re-run this target if you change the Go API types."; \
	fi

# ---------------------------------------------------------------------------
# Go build/test/lint
# ---------------------------------------------------------------------------

.PHONY: fmt
fmt: ## Run go fmt against the code.
	go fmt ./...

.PHONY: vet
vet: ## Run go vet against the code.
	go vet ./...

.PHONY: test
test: fmt vet ## Run unit tests with race detection and coverage.
	go test ./... -race -coverprofile=cover.out

.PHONY: build
build: build-manager build-agent build-gui ## Build all three binaries into bin/.

.PHONY: build-manager
build-manager: ## Build the operator manager binary.
	mkdir -p bin
	CGO_ENABLED=0 go build -o bin/manager .

.PHONY: build-agent
build-agent: ## Build the sidecar agent binary.
	mkdir -p bin
	CGO_ENABLED=0 go build -o bin/agent ./cmd/agent

.PHONY: build-gui
build-gui: ## Build the GUI binary (skipped if cmd/gui doesn't exist yet).
	@if [ -d cmd/gui ]; then \
		mkdir -p bin; \
		CGO_ENABLED=0 go build -o bin/gui ./cmd/gui; \
	else \
		echo ">> cmd/gui not present yet -- skipping build-gui."; \
	fi

.PHONY: run
run: ## Run the operator manager locally against the current kubeconfig context.
	go run ./main.go

# ---------------------------------------------------------------------------
# Docker images
# ---------------------------------------------------------------------------

.PHONY: docker-build
docker-build: docker-build-manager docker-build-agent docker-build-gui ## Build all three images.

.PHONY: docker-build-manager
docker-build-manager:
	docker build -t $(IMG) -f Dockerfile .

.PHONY: docker-build-agent
docker-build-agent:
	docker build -t $(AGENT_IMG) -f Dockerfile.agent .

.PHONY: docker-build-gui
docker-build-gui:
	@if [ -f Dockerfile.gui ]; then \
		docker build -t $(GUI_IMG) -f Dockerfile.gui .; \
	else \
		echo ">> Dockerfile.gui not present yet -- skipping docker-build-gui."; \
	fi

.PHONY: docker-push
docker-push: docker-push-manager docker-push-agent docker-push-gui ## Push all three images.

.PHONY: docker-push-manager
docker-push-manager:
	docker push $(IMG)

.PHONY: docker-push-agent
docker-push-agent:
	docker push $(AGENT_IMG)

.PHONY: docker-push-gui
docker-push-gui:
	@if [ -f Dockerfile.gui ]; then \
		docker push $(GUI_IMG); \
	else \
		echo ">> Dockerfile.gui not present yet -- skipping docker-push-gui."; \
	fi

# ---------------------------------------------------------------------------
# Deploy (kustomize via kubectl -k)
# ---------------------------------------------------------------------------

.PHONY: install
install: ## Install the CRDs into the cluster pointed at by the current kubeconfig context.
	kubectl apply -k config/crd

.PHONY: uninstall
uninstall: ## Remove the CRDs from the cluster (also deletes any KividbCluster objects!).
	kubectl delete -k config/crd --ignore-not-found

.PHONY: deploy
deploy: ## Deploy the operator (CRDs + RBAC + manager Deployment) to the cluster.
	cd config/manager && { command -v kustomize >/dev/null 2>&1 && kustomize edit set image manager=$(IMG) || true; }
	kubectl apply -k config/default

.PHONY: undeploy
undeploy: ## Remove the operator deployment from the cluster.
	kubectl delete -k config/default --ignore-not-found

# ---------------------------------------------------------------------------
# Helm
# ---------------------------------------------------------------------------

.PHONY: helm-lint
helm-lint: ## Lint the Helm chart.
	helm lint $(CHART_DIR)

.PHONY: helm-template
helm-template: ## Render the Helm chart with default values (sanity check).
	helm template kividb-operator $(CHART_DIR)

.PHONY: helm-package
helm-package: ## Package the Helm chart into a .tgz using the version in Chart.yaml.
	helm package $(CHART_DIR) --destination dist/

# ---------------------------------------------------------------------------
# Minikube e2e / compat (hack/e2e)
# ---------------------------------------------------------------------------

.PHONY: e2e e2e-prereqs e2e-deploy
e2e: ## Run full minikube e2e suite
	./hack/e2e/run-all.sh

e2e-prereqs: ## Check kubectl/helm/minikube/docker/redis-cli and minikube status
	./hack/e2e/00-prereqs.sh

e2e-deploy: ## Helm-install the operator into minikube (local image tags)
	./hack/e2e/01-deploy-operator.sh

# ---------------------------------------------------------------------------
# Misc
# ---------------------------------------------------------------------------

.PHONY: clean
clean: ## Remove build artifacts.
	rm -rf bin/ dist/ cover.out

.PHONY: help
help: ## Show this help.
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'
