apiVersion: apps/v1
kind: Deployment
metadata:
  name: kividb-operator-manager
  namespace: kividb-operator-system
  labels:
    app.kubernetes.io/name: kividb-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: kividb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kividb-operator
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kividb-operator
        app.kubernetes.io/component: manager
        app.kubernetes.io/managed-by: kividb-operator
    spec:
      serviceAccountName: kividb-operator-manager
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: manager
          image: quay.io/kividbio/kividb-operator:0.3.0
          imagePullPolicy: IfNotPresent
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8080
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: probes
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      terminationGracePeriodSeconds: 10
