package controller

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	kividbv1alpha1 "github.com/kividbio/kividb-operator/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// renderKividbConf renders kividb's flat "key value" config file format
// (see src/config.rs:apply_config_file upstream) from the free-form
// KividbConfig map plus the fields the operator itself must pin (port,
// aclfile). Directives are emitted in sorted-key order so the generated
// ConfigMap is deterministic and diffs cleanly.
//
// Deliberately absent: "replicaof". Replication topology is not static --
// it is driven at runtime by the operator via the agent's REPLICAOF calls,
// so baking a replicaof directive into the config file would fight the
// controller on every pod restart.
func renderKividbConf(c *kividbv1alpha1.KividbCluster) string {
	directives := map[string]string{}
	for k, v := range c.Spec.KividbConfig {
		if strings.EqualFold(k, "replicaof") || strings.EqualFold(k, "port") || strings.EqualFold(k, "aclfile") {
			continue // operator-owned, see below
		}
		directives[k] = v
	}

	port := c.Spec.Port
	if port == 0 {
		port = 6380
	}
	directives["port"] = strconv.Itoa(int(port))
	directives["aclfile"] = AclDir + "/" + AclFileName

	keys := make([]string, 0, len(directives))
	for k := range directives {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by kividb-operator. Do not edit; changes will be overwritten.\n")
	b.WriteString(fmt.Sprintf("# Source: KividbCluster %s/%s\n\n", c.Namespace, c.Name))
	for _, k := range keys {
		b.WriteString(k)
		b.WriteString(" ")
		b.WriteString(directives[k])
		b.WriteString("\n")
	}
	return b.String()
}

func desiredConfigMap(c *kividbv1alpha1.KividbCluster) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      configMapName(c),
			Namespace: c.Namespace,
			Labels:    commonLabels(c),
		},
		Data: map[string]string{
			ConfigFileName: renderKividbConf(c),
		},
	}
}
