package controller

import (
	"strings"
	"testing"

	kividbv1alpha1 "github.com/kividbio/kividb-operator/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func testCluster(name string) *kividbv1alpha1.KividbCluster {
	return &kividbv1alpha1.KividbCluster{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: "default"},
		Spec:       kividbv1alpha1.KividbClusterSpec{Port: 6380},
	}
}

func TestRenderKividbConf(t *testing.T) {
	t.Parallel()

	t.Run("pins port and aclfile", func(t *testing.T) {
		t.Parallel()
		c := testCluster("demo")
		c.Spec.Port = 7000
		got := renderKividbConf(c, nil)
		if !strings.Contains(got, "port 7000\n") {
			t.Fatalf("expected pinned port 7000, got:\n%s", got)
		}
		wantACL := "aclfile " + AclDir + "/" + AclFileName + "\n"
		if !strings.Contains(got, wantACL) {
			t.Fatalf("expected pinned aclfile, got:\n%s", got)
		}
	})

	t.Run("strips user-supplied replicaof/port/aclfile", func(t *testing.T) {
		t.Parallel()
		c := testCluster("demo")
		cfg := &kividbv1alpha1.KividbConfig{
			Spec: kividbv1alpha1.KividbConfigSpec{
				Directives: map[string]string{
					"replicaof": "10.0.0.1 6380",
					"port":      "9999",
					"aclfile":   "/evil/path",
					"maxmemory": "1gb",
					"loglevel":  "notice",
				},
			},
		}
		got := renderKividbConf(c, cfg)
		if strings.Contains(got, "replicaof") {
			t.Fatalf("replicaof should be stripped, got:\n%s", got)
		}
		if strings.Contains(got, "port 9999") {
			t.Fatalf("user port should be stripped, got:\n%s", got)
		}
		if strings.Contains(got, "/evil/path") {
			t.Fatalf("user aclfile should be stripped, got:\n%s", got)
		}
		if !strings.Contains(got, "port 6380\n") {
			t.Fatalf("operator port should be pinned, got:\n%s", got)
		}
		if !strings.Contains(got, "maxmemory 1gb\n") || !strings.Contains(got, "loglevel notice\n") {
			t.Fatalf("non-owned directives should remain, got:\n%s", got)
		}
	})

	t.Run("emits TLS directives when tls.enabled", func(t *testing.T) {
		t.Parallel()
		c := testCluster("demo")
		cfg := &kividbv1alpha1.KividbConfig{
			Spec: kividbv1alpha1.KividbConfigSpec{
				TLS: &kividbv1alpha1.KividbTLSSpec{
					Enabled: true,
					Port:    7443,
					CertSecretRef: kividbv1alpha1.TLSSecretRef{
						Name:  "tls-secret",
						CAKey: "ca.crt",
					},
				},
			},
		}
		got := renderKividbConf(c, cfg)
		for _, line := range []string{
			"tls-port 7443\n",
			"tls-cert-file " + TLSDir + "/tls.crt\n",
			"tls-key-file " + TLSDir + "/tls.key\n",
			"tls-ca-cert-file " + TLSDir + "/ca.crt\n",
		} {
			if !strings.Contains(got, line) {
				t.Fatalf("missing %q in:\n%s", strings.TrimSpace(line), got)
			}
		}
	})

	t.Run("TLS default port 6443 when unset", func(t *testing.T) {
		t.Parallel()
		c := testCluster("demo")
		cfg := &kividbv1alpha1.KividbConfig{
			Spec: kividbv1alpha1.KividbConfigSpec{
				TLS: &kividbv1alpha1.KividbTLSSpec{Enabled: true},
			},
		}
		got := renderKividbConf(c, cfg)
		if !strings.Contains(got, "tls-port 6443\n") {
			t.Fatalf("expected default tls-port 6443, got:\n%s", got)
		}
		if strings.Contains(got, "tls-ca-cert-file") {
			t.Fatalf("ca cert should be omitted when CAKey empty, got:\n%s", got)
		}
	})

	t.Run("sorted keys, deterministic output", func(t *testing.T) {
		t.Parallel()
		c := testCluster("demo")
		cfg := &kividbv1alpha1.KividbConfig{
			Spec: kividbv1alpha1.KividbConfigSpec{
				Directives: map[string]string{
					"z-last":  "1",
					"a-first": "2",
					"m-mid":   "3",
				},
			},
		}
		got1 := renderKividbConf(c, cfg)
		got2 := renderKividbConf(c, cfg)
		if got1 != got2 {
			t.Fatalf("output not deterministic:\n---\n%s\n---\n%s", got1, got2)
		}
		// Directive keys must appear in lexicographic order among themselves.
		idxA := strings.Index(got1, "a-first ")
		idxACL := strings.Index(got1, "aclfile ")
		idxM := strings.Index(got1, "m-mid ")
		idxPort := strings.Index(got1, "port ")
		idxZ := strings.Index(got1, "z-last ")
		if idxA < 0 || idxACL < 0 || idxM < 0 || idxPort < 0 || idxZ < 0 {
			t.Fatalf("missing expected keys in:\n%s", got1)
		}
		if !(idxA < idxACL && idxACL < idxM && idxM < idxPort && idxPort < idxZ) {
			t.Fatalf("keys not sorted lexicographically:\n%s", got1)
		}
	})

	t.Run("nil kdbConfig still works", func(t *testing.T) {
		t.Parallel()
		c := testCluster("demo")
		got := renderKividbConf(c, nil)
		if !strings.HasPrefix(got, "# Generated by kividb-operator") {
			t.Fatalf("expected generated header, got:\n%s", got)
		}
		if !strings.Contains(got, "port 6380\n") {
			t.Fatalf("expected default port, got:\n%s", got)
		}
		if !strings.Contains(got, "aclfile ") {
			t.Fatalf("expected aclfile, got:\n%s", got)
		}
		if strings.Contains(got, "tls-") {
			t.Fatalf("TLS directives should be absent with nil config, got:\n%s", got)
		}
	})
}
