package controller

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	kividbv1alpha1 "github.com/kividbio/kividb-operator/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// renderKividbConf renders kividb's flat "key value" config file format
// (see src/config.rs:apply_config_file upstream) from the referenced
// KividbConfig's free-form directives plus the fields the operator itself
// must pin (port, aclfile, and TLS if configured). Directives are emitted
// in sorted-key order so the generated ConfigMap is deterministic and
// diffs cleanly.
//
// kdbConfig may be nil (spec.configRef unset) -- kividb's own built-in
// defaults apply, plus whatever the operator itself pins.
//
// Deliberately absent: "replicaof". Replication topology is not static --
// it is driven at runtime by the operator via the agent's REPLICAOF calls,
// so baking a replicaof directive into the config file would fight the
// controller on every pod restart.
func renderKividbConf(c *kividbv1alpha1.KividbCluster, kdbConfig *kividbv1alpha1.KividbConfig) string {
	directives := map[string]string{}
	if kdbConfig != nil {
		for k, v := range kdbConfig.Spec.Directives {
			if strings.EqualFold(k, "replicaof") || strings.EqualFold(k, "port") || strings.EqualFold(k, "aclfile") {
				continue // operator-owned, see below
			}
			directives[k] = v
		}
	}

	port := getPort(c)
	directives["port"] = strconv.Itoa(int(port))
	directives["aclfile"] = AclDir + "/" + AclFileName

	if tls := kividbTLSSpec(kdbConfig); tls != nil && tls.Enabled {
		tlsPort := tls.Port
		if tlsPort == 0 {
			tlsPort = 6443
		}
		directives["tls-port"] = strconv.Itoa(int(tlsPort))
		directives["tls-cert-file"] = TLSDir + "/tls.crt"
		directives["tls-key-file"] = TLSDir + "/tls.key"
		if tls.CertSecretRef.CAKey != "" {
			directives["tls-ca-cert-file"] = TLSDir + "/ca.crt"
		}
	}

	keys := make([]string, 0, len(directives))
	for k := range directives {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by kividb-operator. Do not edit; changes will be overwritten.\n")
	b.WriteString(fmt.Sprintf("# Source: KividbCluster %s/%s\n\n", c.Namespace, c.Name))
	for _, k := range keys {
		b.WriteString(k)
		b.WriteString(" ")
		b.WriteString(directives[k])
		b.WriteString("\n")
	}
	return b.String()
}

// kividbTLSSpec safely extracts the TLS spec from a possibly-nil
// KividbConfig.
func kividbTLSSpec(kdbConfig *kividbv1alpha1.KividbConfig) *kividbv1alpha1.KividbTLSSpec {
	if kdbConfig == nil {
		return nil
	}
	return kdbConfig.Spec.TLS
}

func desiredConfigMap(c *kividbv1alpha1.KividbCluster, kdbConfig *kividbv1alpha1.KividbConfig) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      configMapName(c),
			Namespace: c.Namespace,
			Labels:    commonLabels(c),
		},
		Data: map[string]string{
			ConfigFileName: renderKividbConf(c, kdbConfig),
		},
	}
}
