package controller

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"

	kividbv1alpha1 "github.com/kividbio/kividb-operator/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// secretValueKey uniquely identifies one key within one Secret, used as a
// map key when the controller pre-fetches every password referenced by
// KividbClusterSpec.Auth before rendering the ACL file.
func secretValueKey(ref *kividbv1alpha1.SecretKeyRef) string {
	if ref == nil {
		return ""
	}
	return ref.Name + "/" + ref.Key
}

// hashPassword mirrors kividb's own password hashing (SHA-256 hex, see
// upstream src/acl.rs AclUser) so the rendered ACL file's "#<hash>" entries
// are accepted exactly like a plaintext `ACL SETUSER ... >password` would
// produce.
func hashPassword(plaintext string) string {
	sum := sha256.Sum256([]byte(plaintext))
	return hex.EncodeToString(sum[:])
}

func boolOr(p *bool, def bool) bool {
	if p == nil {
		return def
	}
	return *p
}

func joinOrDefault(vals []string, def string) string {
	if len(vals) == 0 {
		return def
	}
	return strings.Join(vals, " ")
}

// renderUserLine renders one Redis/kividb-ACL-file line:
//
//	user <name> <on|off> <nopass|#hash> <keypatterns> <channelpatterns> <cmdrules>
func renderUserLine(u kividbv1alpha1.KividbUser, secretValues map[string]string) (string, error) {
	onOff := "on"
	if !boolOr(u.Enabled, true) {
		onOff = "off"
	}

	authToken := "nopass"
	if !u.NoPass {
		if u.PasswordSecretRef == nil {
			return "", fmt.Errorf("user %q: must set noPass or passwordSecretRef", u.Name)
		}
		plaintext, ok := secretValues[secretValueKey(u.PasswordSecretRef)]
		if !ok {
			return "", fmt.Errorf("user %q: password secret %s/%s not found", u.Name, u.PasswordSecretRef.Name, u.PasswordSecretRef.Key)
		}
		authToken = "#" + hashPassword(plaintext)
	}

	keyPatterns := joinOrDefault(u.KeyPatterns, "~*")
	channelPatterns := joinOrDefault(u.ChannelPatterns, "&*")
	cmdRules := joinOrDefault(u.CommandRules, "+@all")

	return fmt.Sprintf("user %s %s %s %s %s %s", u.Name, onOff, authToken, keyPatterns, channelPatterns, cmdRules), nil
}

// renderACLFile renders the full ACL file body for a KividbCluster. If the
// user list contains no "default" entry, a permissive default user is
// synthesized (nopass, +@all) unless RequirePassSecretRef is set, in which
// case the default user is authenticated by that password -- matching
// kividb's own AclUser::default_user derivation from --requirepass.
func renderACLFile(c *kividbv1alpha1.KividbCluster, secretValues map[string]string) (string, error) {
	users := append([]kividbv1alpha1.KividbUser{}, c.Spec.Auth.Users...)

	hasDefault := false
	for _, u := range users {
		if u.Name == "default" {
			hasDefault = true
			break
		}
	}
	if !hasDefault {
		def := kividbv1alpha1.KividbUser{Name: "default"}
		if c.Spec.Auth.RequirePassSecretRef != nil {
			def.PasswordSecretRef = c.Spec.Auth.RequirePassSecretRef
		} else {
			def.NoPass = true
		}
		users = append([]kividbv1alpha1.KividbUser{def}, users...)
	}

	var b strings.Builder
	b.WriteString("# Generated by kividb-operator. Do not edit; changes will be overwritten.\n")
	for _, u := range users {
		line, err := renderUserLine(u, secretValues)
		if err != nil {
			return "", err
		}
		b.WriteString(line)
		b.WriteString("\n")
	}
	return b.String(), nil
}

// collectSecretRefs returns every SecretKeyRef the controller must resolve
// before it can render the ACL file: the default-user requirepass ref plus
// each explicit user's password ref.
func collectSecretRefs(c *kividbv1alpha1.KividbCluster) []*kividbv1alpha1.SecretKeyRef {
	var refs []*kividbv1alpha1.SecretKeyRef
	if c.Spec.Auth.RequirePassSecretRef != nil {
		refs = append(refs, c.Spec.Auth.RequirePassSecretRef)
	}
	for i := range c.Spec.Auth.Users {
		if c.Spec.Auth.Users[i].PasswordSecretRef != nil {
			refs = append(refs, c.Spec.Auth.Users[i].PasswordSecretRef)
		}
	}
	return refs
}

// defaultUserPasswordRef returns the SecretKeyRef backing the "default"
// ACL user's password, if any: an explicit "default" entry in Auth.Users
// takes precedence over Auth.RequirePassSecretRef. The agent sidecar uses
// this same ref (injected as an env var) to authenticate its own local
// RESP connections, so it always matches what renderACLFile put on disk.
func defaultUserPasswordRef(c *kividbv1alpha1.KividbCluster) *kividbv1alpha1.SecretKeyRef {
	for i := range c.Spec.Auth.Users {
		if c.Spec.Auth.Users[i].Name == "default" {
			if c.Spec.Auth.Users[i].NoPass {
				return nil
			}
			return c.Spec.Auth.Users[i].PasswordSecretRef
		}
	}
	return c.Spec.Auth.RequirePassSecretRef
}

func desiredAuthSecret(c *kividbv1alpha1.KividbCluster, aclContent string) *corev1.Secret {
	return &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      secretName(c),
			Namespace: c.Namespace,
			Labels:    commonLabels(c),
		},
		Type: corev1.SecretTypeOpaque,
		StringData: map[string]string{
			AclFileName: aclContent,
		},
	}
}
