apiVersion: v1
kind: ServiceAccount
metadata:
  name: kividb-operator-manager
  namespace: kividb-operator-system
  labels:
    app.kubernetes.io/name: kividb-operator
    app.kubernetes.io/managed-by: kividb-operator
