{{- if .Values.gui.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kividb-operator.gui.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kividb-operator.gui.labels" . | nindent 4 }}
{{- end }}
