//go:build !ignore_autogenerated

// Code generated by hand to mirror controller-gen's object-deepcopy output.
// Run `make generate` (which shells out to controller-gen, when available)
// to regenerate this file mechanically instead of hand-editing it further.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of
// the same type that is provided as a pointer.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy creates a new SecretKeyRef by deep-copying the receiver.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbUser) DeepCopyInto(out *KividbUser) {
	*out = *in
	if in.Enabled != nil {
		out.Enabled = new(bool)
		*out.Enabled = *in.Enabled
	}
	if in.PasswordSecretRef != nil {
		out.PasswordSecretRef = new(SecretKeyRef)
		*out.PasswordSecretRef = *in.PasswordSecretRef
	}
	if in.KeyPatterns != nil {
		out.KeyPatterns = make([]string, len(in.KeyPatterns))
		copy(out.KeyPatterns, in.KeyPatterns)
	}
	if in.ChannelPatterns != nil {
		out.ChannelPatterns = make([]string, len(in.ChannelPatterns))
		copy(out.ChannelPatterns, in.ChannelPatterns)
	}
	if in.CommandRules != nil {
		out.CommandRules = make([]string, len(in.CommandRules))
		copy(out.CommandRules, in.CommandRules)
	}
}

func (in *KividbUser) DeepCopy() *KividbUser {
	if in == nil {
		return nil
	}
	out := new(KividbUser)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	if in.RequirePassSecretRef != nil {
		out.RequirePassSecretRef = new(SecretKeyRef)
		*out.RequirePassSecretRef = *in.RequirePassSecretRef
	}
	if in.Users != nil {
		out.Users = make([]KividbUser, len(in.Users))
		for i := range in.Users {
			in.Users[i].DeepCopyInto(&out.Users[i])
		}
	}
}

func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.StorageClassName != nil {
		out.StorageClassName = new(string)
		*out.StorageClassName = *in.StorageClassName
	}
	if in.AccessModes != nil {
		out.AccessModes = make([]corev1.PersistentVolumeAccessMode, len(in.AccessModes))
		copy(out.AccessModes, in.AccessModes)
	}
}

func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.LoadBalancerSourceRanges != nil {
		out.LoadBalancerSourceRanges = make([]string, len(in.LoadBalancerSourceRanges))
		copy(out.LoadBalancerSourceRanges, in.LoadBalancerSourceRanges)
	}
	if in.Annotations != nil {
		out.Annotations = make(map[string]string, len(in.Annotations))
		for k, v := range in.Annotations {
			out.Annotations[k] = v
		}
	}
}

func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ServicesSpec) DeepCopyInto(out *ServicesSpec) {
	*out = *in
	in.Master.DeepCopyInto(&out.Master)
	in.Replicas.DeepCopyInto(&out.Replicas)
}

func (in *ServicesSpec) DeepCopy() *ServicesSpec {
	if in == nil {
		return nil
	}
	out := new(ServicesSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *S3CredentialsSecretRef) DeepCopyInto(out *S3CredentialsSecretRef) {
	*out = *in
}

func (in *S3CredentialsSecretRef) DeepCopy() *S3CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(S3CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *S3StorageSpec) DeepCopyInto(out *S3StorageSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

func (in *S3StorageSpec) DeepCopy() *S3StorageSpec {
	if in == nil {
		return nil
	}
	out := new(S3StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	if in.TimeoutSeconds != nil {
		out.TimeoutSeconds = new(int32)
		*out.TimeoutSeconds = *in.TimeoutSeconds
	}
	if in.S3 != nil {
		out.S3 = new(S3StorageSpec)
		in.S3.DeepCopyInto(out.S3)
	}
	in.JobResources.DeepCopyInto(&out.JobResources)
}

func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *FailoverSpec) DeepCopyInto(out *FailoverSpec) {
	*out = *in
	if in.Enabled != nil {
		out.Enabled = new(bool)
		*out.Enabled = *in.Enabled
	}
	if in.UnhealthyThresholdSeconds != nil {
		out.UnhealthyThresholdSeconds = new(int32)
		*out.UnhealthyThresholdSeconds = *in.UnhealthyThresholdSeconds
	}
}

func (in *FailoverSpec) DeepCopy() *FailoverSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbClusterSpec) DeepCopyInto(out *KividbClusterSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		out.ImagePullSecrets = make([]corev1.LocalObjectReference, len(in.ImagePullSecrets))
		copy(out.ImagePullSecrets, in.ImagePullSecrets)
	}
	if in.KividbConfig != nil {
		out.KividbConfig = make(map[string]string, len(in.KividbConfig))
		for k, v := range in.KividbConfig {
			out.KividbConfig[k] = v
		}
	}
	in.Auth.DeepCopyInto(&out.Auth)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	in.AgentResources.DeepCopyInto(&out.AgentResources)
	in.ExporterResources.DeepCopyInto(&out.ExporterResources)
	if in.Tolerations != nil {
		out.Tolerations = make([]corev1.Toleration, len(in.Tolerations))
		for i := range in.Tolerations {
			in.Tolerations[i].DeepCopyInto(&out.Tolerations[i])
		}
	}
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.Affinity != nil {
		out.Affinity = in.Affinity.DeepCopy()
	}
	if in.PodAnnotations != nil {
		out.PodAnnotations = make(map[string]string, len(in.PodAnnotations))
		for k, v := range in.PodAnnotations {
			out.PodAnnotations[k] = v
		}
	}
	if in.PodLabels != nil {
		out.PodLabels = make(map[string]string, len(in.PodLabels))
		for k, v := range in.PodLabels {
			out.PodLabels[k] = v
		}
	}
	if in.TerminationGracePeriodSeconds != nil {
		out.TerminationGracePeriodSeconds = new(int64)
		*out.TerminationGracePeriodSeconds = *in.TerminationGracePeriodSeconds
	}
	in.Services.DeepCopyInto(&out.Services)
	in.Backup.DeepCopyInto(&out.Backup)
	out.Monitoring = in.Monitoring
	in.Failover.DeepCopyInto(&out.Failover)
}

func (in *KividbClusterSpec) DeepCopy() *KividbClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KividbClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbPodStatus) DeepCopyInto(out *KividbPodStatus) {
	*out = *in
}

func (in *KividbPodStatus) DeepCopy() *KividbPodStatus {
	if in == nil {
		return nil
	}
	out := new(KividbPodStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	if in.LastRunTime != nil {
		out.LastRunTime = in.LastRunTime.DeepCopy()
	}
	if in.LastSuccessTime != nil {
		out.LastSuccessTime = in.LastSuccessTime.DeepCopy()
	}
}

func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbClusterStatus) DeepCopyInto(out *KividbClusterStatus) {
	*out = *in
	if in.Pods != nil {
		out.Pods = make([]KividbPodStatus, len(in.Pods))
		copy(out.Pods, in.Pods)
	}
	if in.LastFailoverTime != nil {
		out.LastFailoverTime = in.LastFailoverTime.DeepCopy()
	}
	in.Backup.DeepCopyInto(&out.Backup)
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *KividbClusterStatus) DeepCopy() *KividbClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KividbClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbCluster) DeepCopyInto(out *KividbCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KividbCluster) DeepCopy() *KividbCluster {
	if in == nil {
		return nil
	}
	out := new(KividbCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KividbClusterList) DeepCopyInto(out *KividbClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KividbCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KividbClusterList) DeepCopy() *KividbClusterList {
	if in == nil {
		return nil
	}
	out := new(KividbClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
