//go:build !ignore_autogenerated

// Code generated by hand to mirror controller-gen's object-deepcopy output.
// Run `make generate` (which shells out to controller-gen, when available)
// to regenerate this file mechanically instead of hand-editing it further.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ── shared / kividbcluster_types.go ─────────────────────────────────────

func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbUser) DeepCopyInto(out *KividbUser) {
	*out = *in
	if in.Enabled != nil {
		out.Enabled = new(bool)
		*out.Enabled = *in.Enabled
	}
	if in.PasswordSecretRef != nil {
		out.PasswordSecretRef = new(SecretKeyRef)
		*out.PasswordSecretRef = *in.PasswordSecretRef
	}
	if in.KeyPatterns != nil {
		out.KeyPatterns = make([]string, len(in.KeyPatterns))
		copy(out.KeyPatterns, in.KeyPatterns)
	}
	if in.ChannelPatterns != nil {
		out.ChannelPatterns = make([]string, len(in.ChannelPatterns))
		copy(out.ChannelPatterns, in.ChannelPatterns)
	}
	if in.CommandRules != nil {
		out.CommandRules = make([]string, len(in.CommandRules))
		copy(out.CommandRules, in.CommandRules)
	}
}

func (in *KividbUser) DeepCopy() *KividbUser {
	if in == nil {
		return nil
	}
	out := new(KividbUser)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.StorageClassName != nil {
		out.StorageClassName = new(string)
		*out.StorageClassName = *in.StorageClassName
	}
	if in.AccessModes != nil {
		out.AccessModes = make([]corev1.PersistentVolumeAccessMode, len(in.AccessModes))
		copy(out.AccessModes, in.AccessModes)
	}
}

func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.LoadBalancerSourceRanges != nil {
		out.LoadBalancerSourceRanges = make([]string, len(in.LoadBalancerSourceRanges))
		copy(out.LoadBalancerSourceRanges, in.LoadBalancerSourceRanges)
	}
	if in.Annotations != nil {
		out.Annotations = make(map[string]string, len(in.Annotations))
		for k, v := range in.Annotations {
			out.Annotations[k] = v
		}
	}
}

func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ServicesSpec) DeepCopyInto(out *ServicesSpec) {
	*out = *in
	in.Master.DeepCopyInto(&out.Master)
	in.Replicas.DeepCopyInto(&out.Replicas)
}

func (in *ServicesSpec) DeepCopy() *ServicesSpec {
	if in == nil {
		return nil
	}
	out := new(ServicesSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *FailoverSpec) DeepCopyInto(out *FailoverSpec) {
	*out = *in
	if in.Enabled != nil {
		out.Enabled = new(bool)
		*out.Enabled = *in.Enabled
	}
	if in.UnhealthyThresholdSeconds != nil {
		out.UnhealthyThresholdSeconds = new(int32)
		*out.UnhealthyThresholdSeconds = *in.UnhealthyThresholdSeconds
	}
}

func (in *FailoverSpec) DeepCopy() *FailoverSpec {
	if in == nil {
		return nil
	}
	out := new(FailoverSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbClusterSpec) DeepCopyInto(out *KividbClusterSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		out.ImagePullSecrets = make([]corev1.LocalObjectReference, len(in.ImagePullSecrets))
		copy(out.ImagePullSecrets, in.ImagePullSecrets)
	}
	if in.ConfigRef != nil {
		out.ConfigRef = new(corev1.LocalObjectReference)
		*out.ConfigRef = *in.ConfigRef
	}
	if in.AclConfigRef != nil {
		out.AclConfigRef = new(corev1.LocalObjectReference)
		*out.AclConfigRef = *in.AclConfigRef
	}
	if in.SnapshotConfigRef != nil {
		out.SnapshotConfigRef = new(corev1.LocalObjectReference)
		*out.SnapshotConfigRef = *in.SnapshotConfigRef
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	in.AgentResources.DeepCopyInto(&out.AgentResources)
	in.ExporterResources.DeepCopyInto(&out.ExporterResources)
	if in.Tolerations != nil {
		out.Tolerations = make([]corev1.Toleration, len(in.Tolerations))
		for i := range in.Tolerations {
			in.Tolerations[i].DeepCopyInto(&out.Tolerations[i])
		}
	}
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.Affinity != nil {
		out.Affinity = in.Affinity.DeepCopy()
	}
	if in.PodAnnotations != nil {
		out.PodAnnotations = make(map[string]string, len(in.PodAnnotations))
		for k, v := range in.PodAnnotations {
			out.PodAnnotations[k] = v
		}
	}
	if in.PodLabels != nil {
		out.PodLabels = make(map[string]string, len(in.PodLabels))
		for k, v := range in.PodLabels {
			out.PodLabels[k] = v
		}
	}
	if in.TerminationGracePeriodSeconds != nil {
		out.TerminationGracePeriodSeconds = new(int64)
		*out.TerminationGracePeriodSeconds = *in.TerminationGracePeriodSeconds
	}
	in.Services.DeepCopyInto(&out.Services)
	out.Monitoring = in.Monitoring
	in.Failover.DeepCopyInto(&out.Failover)
}

func (in *KividbClusterSpec) DeepCopy() *KividbClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KividbClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbPodStatus) DeepCopyInto(out *KividbPodStatus) {
	*out = *in
}

func (in *KividbPodStatus) DeepCopy() *KividbPodStatus {
	if in == nil {
		return nil
	}
	out := new(KividbPodStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbClusterStatus) DeepCopyInto(out *KividbClusterStatus) {
	*out = *in
	if in.Pods != nil {
		out.Pods = make([]KividbPodStatus, len(in.Pods))
		copy(out.Pods, in.Pods)
	}
	if in.LastFailoverTime != nil {
		out.LastFailoverTime = in.LastFailoverTime.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *KividbClusterStatus) DeepCopy() *KividbClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KividbClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbCluster) DeepCopyInto(out *KividbCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KividbCluster) DeepCopy() *KividbCluster {
	if in == nil {
		return nil
	}
	out := new(KividbCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KividbClusterList) DeepCopyInto(out *KividbClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KividbCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KividbClusterList) DeepCopy() *KividbClusterList {
	if in == nil {
		return nil
	}
	out := new(KividbClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── kividbconfig_types.go ────────────────────────────────────────────────

func (in *TLSSecretRef) DeepCopyInto(out *TLSSecretRef) {
	*out = *in
}

func (in *TLSSecretRef) DeepCopy() *TLSSecretRef {
	if in == nil {
		return nil
	}
	out := new(TLSSecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbTLSSpec) DeepCopyInto(out *KividbTLSSpec) {
	*out = *in
	out.CertSecretRef = in.CertSecretRef
}

func (in *KividbTLSSpec) DeepCopy() *KividbTLSSpec {
	if in == nil {
		return nil
	}
	out := new(KividbTLSSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbConfigSpec) DeepCopyInto(out *KividbConfigSpec) {
	*out = *in
	if in.Directives != nil {
		out.Directives = make(map[string]string, len(in.Directives))
		for k, v := range in.Directives {
			out.Directives[k] = v
		}
	}
	if in.TLS != nil {
		out.TLS = new(KividbTLSSpec)
		in.TLS.DeepCopyInto(out.TLS)
	}
}

func (in *KividbConfigSpec) DeepCopy() *KividbConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KividbConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbConfig) DeepCopyInto(out *KividbConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *KividbConfig) DeepCopy() *KividbConfig {
	if in == nil {
		return nil
	}
	out := new(KividbConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KividbConfigList) DeepCopyInto(out *KividbConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KividbConfig, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KividbConfigList) DeepCopy() *KividbConfigList {
	if in == nil {
		return nil
	}
	out := new(KividbConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── kividbaclconfig_types.go ────────────────────────────────────────────

func (in *KividbAclConfigSpec) DeepCopyInto(out *KividbAclConfigSpec) {
	*out = *in
	if in.RequirePassSecretRef != nil {
		out.RequirePassSecretRef = new(SecretKeyRef)
		*out.RequirePassSecretRef = *in.RequirePassSecretRef
	}
	if in.Users != nil {
		out.Users = make([]KividbUser, len(in.Users))
		for i := range in.Users {
			in.Users[i].DeepCopyInto(&out.Users[i])
		}
	}
}

func (in *KividbAclConfigSpec) DeepCopy() *KividbAclConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KividbAclConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbAclConfig) DeepCopyInto(out *KividbAclConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *KividbAclConfig) DeepCopy() *KividbAclConfig {
	if in == nil {
		return nil
	}
	out := new(KividbAclConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbAclConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KividbAclConfigList) DeepCopyInto(out *KividbAclConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KividbAclConfig, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KividbAclConfigList) DeepCopy() *KividbAclConfigList {
	if in == nil {
		return nil
	}
	out := new(KividbAclConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbAclConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── kividbsnapshotconfig_types.go ───────────────────────────────────────

func (in *S3CredentialsSecretRef) DeepCopyInto(out *S3CredentialsSecretRef) {
	*out = *in
}

func (in *S3CredentialsSecretRef) DeepCopy() *S3CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(S3CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *S3StorageSpec) DeepCopyInto(out *S3StorageSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

func (in *S3StorageSpec) DeepCopy() *S3StorageSpec {
	if in == nil {
		return nil
	}
	out := new(S3StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbSnapshotConfigSpec) DeepCopyInto(out *KividbSnapshotConfigSpec) {
	*out = *in
	if in.TimeoutSeconds != nil {
		out.TimeoutSeconds = new(int32)
		*out.TimeoutSeconds = *in.TimeoutSeconds
	}
	in.S3.DeepCopyInto(&out.S3)
	in.JobResources.DeepCopyInto(&out.JobResources)
}

func (in *KividbSnapshotConfigSpec) DeepCopy() *KividbSnapshotConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KividbSnapshotConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbSnapshotConfig) DeepCopyInto(out *KividbSnapshotConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *KividbSnapshotConfig) DeepCopy() *KividbSnapshotConfig {
	if in == nil {
		return nil
	}
	out := new(KividbSnapshotConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbSnapshotConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KividbSnapshotConfigList) DeepCopyInto(out *KividbSnapshotConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KividbSnapshotConfig, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KividbSnapshotConfigList) DeepCopy() *KividbSnapshotConfigList {
	if in == nil {
		return nil
	}
	out := new(KividbSnapshotConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbSnapshotConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── kividbsnapshot_types.go ─────────────────────────────────────────────

func (in *KividbSnapshotSpec) DeepCopyInto(out *KividbSnapshotSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	out.SnapshotConfigRef = in.SnapshotConfigRef
}

func (in *KividbSnapshotSpec) DeepCopy() *KividbSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(KividbSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbSnapshotStatus) DeepCopyInto(out *KividbSnapshotStatus) {
	*out = *in
	if in.StartTime != nil {
		out.StartTime = in.StartTime.DeepCopy()
	}
	if in.CompletionTime != nil {
		out.CompletionTime = in.CompletionTime.DeepCopy()
	}
}

func (in *KividbSnapshotStatus) DeepCopy() *KividbSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(KividbSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbSnapshot) DeepCopyInto(out *KividbSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KividbSnapshot) DeepCopy() *KividbSnapshot {
	if in == nil {
		return nil
	}
	out := new(KividbSnapshot)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KividbSnapshotList) DeepCopyInto(out *KividbSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KividbSnapshot, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KividbSnapshotList) DeepCopy() *KividbSnapshotList {
	if in == nil {
		return nil
	}
	out := new(KividbSnapshotList)
	in.DeepCopyInto(out)
	return out
}

func (in *KividbSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
